INSERT INTO public.waste_manager_address(CREATED_DATE,DIRECCION,IS_ENABLED,LAST_MODIFIED_DATE,VERSION)
VALUES (NOW(),'PASSATGE REAL, 15',TRUE,NOW(),0);

INSERT INTO public.waste_manager_address(CREATED_DATE,DIRECCION,IS_ENABLED,LAST_MODIFIED_DATE,VERSION)
VALUES (NOW(),'CARRETERA CATALUNYA, 36',TRUE,NOW(),0);

INSERT INTO public.waste_manager_address(CREATED_DATE,DIRECCION,IS_ENABLED,LAST_MODIFIED_DATE,VERSION)
VALUES (NOW(),'KALEA CATALUNYA, 99',TRUE,NOW(),0);